#!/usr/bin/env bash
# =========================================
# .FILE
#   linux_backup.sh
#
# .SYNOPSIS
#   Linux backup script file
#
# .DESCRIPTION
#   It hold linux softwares/tips that i used
#
# .INPUTS
#   None
#
# .OUTPUTS
#   None
#
# .NOTES
#   Version       : 1.0
#   Author        : @ZouariOmar <zouariomar20@gmail.com>
#   Created       : <09/11/2025>
#   Change Log    : Initial version
#
# .EXAMPLE
#   ./linux_backup
# =========================================

# Change bash font (Oh My BASH!) || !OR USE "Oh My Posh!"
bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

# Setup git
git config --global user.email "zouariomar20@gmail.com"
git config --global user.username "Zouari Omar"
git config --global user.name "Zouari Omar"

# Install ollama
curl -fsSL https://ollama.com/install.sh | sh
curl https://raw.githubusercontent.com/ollama/ollama/refs/heads/main/docs/linux.md                    # Unistall ollama
curl https://raw.githubusercontent.com/jmont-dev/ollama-hpp/refs/heads/master/singleheader/ollama.hpp # Install ollama.hpp

# Basic installation for oracle-xe on archlinux
firefox https://gist.github.com/davidmaignan/d0d941cbf761678457b865e6de041af0

# Install dlib (C++ toolkit containing machine learning algorithms)
git clone https://github.com/davisking/dlib.git
cd dlib || exit 1
mkdir build
cd build || exit 1
cmake ..
cmake --build .
sudo cmake --install .

# Install n³ plugins
# See https://github.com/jarun/nnn/tree/master/plugins
# Plugins are installed to `${XDG_CONFIG_HOME:-$HOME/.config}/nnn/plugins`
sh -c "$(curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs)" # The following command installs or updates (after backup) all plugins
export NNN_PLUG='f:finder;o:fzopen;p:mocq;d:diffs;t:nmount;v:imgview'                   # Set environment variable NNN_PLUG to assign keybinds and invoke plugins directly using the plugin shortcut (;) followed by the assigned key character

# Install pio-cli and make executable globally (See https://docs.platformio.org/en/latest/core/index.html)
curl -fsSL -o get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
python3 get-platformio.py
echo "export PATH=$PATH:$HOME/.local/bin" >>~/.bashrc
sudo ln -s ~/.platformio/penv/bin/platformio ~/.local/bin/platformio
sudo ln -s ~/.platformio/penv/bin/pio ~/.local/bin/pio
sudo ln -s ~/.platformio/penv/bin/piodebuggdb ~/.local/bin/piodebuggdb

# Install sdkman (i use it to install GraalVM)
curl -s "https://get.sdkman.io" | bash

# Install Symfony using wget
wget https://get.symfony.com/cli/installer -O - | bash
# Or using curl
curl -sS https://get.symfony.com/cli/installer | bash

# Install live server
npm install -g live-server

# Install browder sync (support proxy server)
npm install -g browser-sync

# Install copilot-cli
curl -fsSL https://gh.io/copilot-install | bash

# Install tigervnc
sudo pacman -Sy tigervnc
