#!/usr/bin/env bash
# =========================================
# .FILE
#   install_all
#
# .SYNOPSIS
#   Install and configure all dotfiles on a new system.
#
# .DESCRIPTION
#   This script sets up a complete development environment by installing
#   required dependencies and creating symlinks for all dotfiles included
#   in this repository (shell, editor, git, tools, etc.).
#
# .PARAMETER none
#   none
#
# .INPUTS
#   None
#
# .OUTPUTS
#   Console output and optional log file.
#
# .NOTES
#   Version       : 1.0
#   Author        : @ZouariOmar <zouariomar20@gmail.com>
#   Created       : 2026-01-01
#   Change Log    : Initial version
#
# .EXAMPLE
#   ./install_all
# =========================================
